import React, { useState, useEffect } from 'react';
import { CONFIG } from '../config';

interface Student {
  id: string;
  name: string;
  currentBook: string;
  progress: string;
  grade: string;
}

export default function ReportManage() {
  const [students, setStudents] = useState<Student[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedStudent, setSelectedStudent] = useState<Student | null>(null);
  
  const [editBook, setEditBook] = useState('');
  const [editProgress, setEditProgress] = useState('');
  const [isSaving, setIsSaving] = useState(false);

  const [finalReportText, setFinalReportText] = useState('');

  // 1. 학생 명단 불러오기 (💡 5분 딜레이가 있는 CSV 대신, 백엔드에서 실시간으로 직접 가져옵니다!)
  const fetchStudents = async () => {
    try {
      setIsLoading(true);
      const payload = { type: "getStudents" };
      
      const response = await fetch(CONFIG.WEB_APP_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain;charset=utf-8' },
        body: JSON.stringify(payload)
      });
      
      const parsedStudents = await response.json();
      
      if (parsedStudents.error) {
        alert("데이터 로드 오류: " + parsedStudents.error);
        return;
      }
      
      setStudents(parsedStudents);
      if (parsedStudents.length > 0) setSelectedStudent(parsedStudents[0]);
    } catch (error) {
      console.error("데이터 로드 실패", error);
      alert("학생 정보를 불러오는데 실패했습니다.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { fetchStudents(); }, []);

  // 2. 학생이 바뀔 때마다 '수정 칸'과 '리포트 템플릿'을 해당 학생 정보로 업데이트
  useEffect(() => {
    if (!selectedStudent) return;
    
    setEditBook(selectedStudent.currentBook || '');
    setEditProgress(selectedStudent.progress || '');

    const today = new Date();
    const weekInfo = `${today.getMonth() + 1}월 ${Math.ceil(today.getDate() / 7)}주차`;
    
    const autoGeneratedText = `안녕하세요 학부모님! 🐋 고래영어입니다.
${selectedStudent.name} 학생의 ${weekInfo} 주간 학습 리포트를 보내드립니다.

━━━━━━━━━━━━━━━━
👤 학생: ${selectedStudent.name} (${selectedStudent.grade})
📖 현재 교재: ${selectedStudent.currentBook}권
🎯 현재 진도: ${selectedStudent.progress}

[이번 주 달성 미션 🏆]
✅ 영단어 완벽 암기 통과
✅ 어순 감각 문장 배열 통과
✅ 핵심 문법 퀴즈 통과
━━━━━━━━━━━━━━━━

💬 원장님 코멘트:
이번 주도 결석 없이 성실하게 학습을 완료했습니다. 가정에서도 우리 ${selectedStudent.name}(이)가 성취감을 느낄 수 있도록 아낌없는 폭풍 칭찬 부탁드립니다! 감사합니다. 🙇‍♂️🙇‍♀️`;

    setFinalReportText(autoGeneratedText);
  }, [selectedStudent]);

  // 3. 구글 시트로 진도 변경 데이터 쏘기
  const handleSaveProgress = async () => {
    if (!selectedStudent) return;
    setIsSaving(true);
    
    const payload = {
      type: "updateProgress",
      studentId: selectedStudent.id,
      currentBook: editBook,
      progress: editProgress,
      sheetName: 'STUDENT_LIST'
    };

    try {
      await fetch(CONFIG.WEB_APP_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain;charset=utf-8' },
        body: JSON.stringify(payload)
      });

      setStudents(prev => prev.map(s => 
        s.id === selectedStudent.id ? { ...s, currentBook: editBook, progress: editProgress } : s
      ));
      setSelectedStudent(prev => prev ? { ...prev, currentBook: editBook, progress: editProgress } : null);
      
      alert(`✅ ${selectedStudent.name} 학생의 진도가 성공적으로 변경되었습니다!`);
    } catch (err) {
      alert("진도 업데이트 중 오류가 발생했습니다.");
    } finally {
      setIsSaving(false);
    }
  };

  // 4. 복사 기능
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(finalReportText);
      alert('복사되었습니다! 카톡에 붙여넣기 하세요.');
    } catch (err) {
      alert('복사 실패');
    }
  };

  return (
    <div style={{ padding: '30px', backgroundColor: '#f8fafc', minHeight: '100vh', fontFamily: 'Pretendard, sans-serif' }}>
      
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <h2 style={{ margin: 0, fontSize: '28px', fontWeight: '800', color: '#0f172a' }}>💌 주말 리포트 & 학생 진도 관리</h2>
        {/* 💡 새로고침 버튼을 만들어 원장님이 언제든 최신 데이터를 당겨올 수 있게 했습니다! */}
        <button 
          onClick={fetchStudents} 
          style={{ padding: '10px 16px', backgroundColor: '#e2e8f0', color: '#1e293b', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer' }}
        >
          🔄 실시간 명단 새로고침
        </button>
      </div>

      {isLoading ? (
        <div style={{ textAlign: 'center', padding: '40px' }}>학생 명단을 실시간으로 불러오는 중입니다...</div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '24px' }}>
          
          {/* 왼쪽: 학생 리스트 */}
          <div style={{ backgroundColor: 'white', border: '1px solid #e2e8f0', borderRadius: '16px', overflow: 'hidden' }}>
            <div style={{ backgroundColor: '#f1f5f9', padding: '16px', fontWeight: 'bold' }}>학생 명단 (실시간 연동)</div>
            <div style={{ maxHeight: '600px', overflowY: 'auto' }}>
              {students.map(student => (
                <div 
                  key={student.id} 
                  onClick={() => setSelectedStudent(student)}
                  style={{ 
                    padding: '16px', borderBottom: '1px solid #f1f5f9', cursor: 'pointer',
                    backgroundColor: selectedStudent?.id === student.id ? '#eff6ff' : 'white',
                    borderLeft: selectedStudent?.id === student.id ? '4px solid #3b82f6' : '4px solid transparent',
                  }}
                >
                  <div style={{ fontWeight: 'bold', fontSize: '16px' }}>{student.name}</div>
                  <div style={{ color: '#64748b', fontSize: '13px' }}>{student.currentBook}권 | {student.progress}</div>
                </div>
              ))}
            </div>
          </div>

          {/* 오른쪽: 진도 수정 및 리포트 편집기 */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
            
            {/* 진도 관리 패널 */}
            {selectedStudent && (
              <div style={{ backgroundColor: 'white', padding: '24px', borderRadius: '16px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)' }}>
                <h3 style={{ margin: '0 0 16px 0', fontSize: '18px', color: '#334155', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  🛠️ <b>{selectedStudent.name}</b> 학생 진도 변경
                </h3>
                
                <div style={{ display: 'flex', gap: '16px', alignItems: 'flex-end' }}>
                  <div style={{ flex: 1 }}>
                    <label style={{ display: 'block', fontSize: '13px', fontWeight: 'bold', color: '#64748b', marginBottom: '8px' }}>현재 교재 (Book)</label>
                    <input 
                      type="text" 
                      value={editBook} 
                      onChange={(e) => setEditBook(e.target.value)}
                      style={{ width: '100%', padding: '12px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '15px', boxSizing: 'border-box' }}
                    />
                  </div>
                  <div style={{ flex: 1 }}>
                    <label style={{ display: 'block', fontSize: '13px', fontWeight: 'bold', color: '#64748b', marginBottom: '8px' }}>상세 진도 (Progress)</label>
                    <input 
                      type="text" 
                      value={editProgress} 
                      onChange={(e) => setEditProgress(e.target.value)}
                      style={{ width: '100%', padding: '12px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '15px', boxSizing: 'border-box' }}
                      placeholder="예: Stage 1 완료"
                    />
                  </div>
                  <button 
                    onClick={handleSaveProgress} 
                    disabled={isSaving}
                    style={{ padding: '12px 24px', backgroundColor: isSaving ? '#94a3b8' : '#3b82f6', color: 'white', border: 'none', borderRadius: '8px', fontSize: '15px', fontWeight: 'bold', cursor: isSaving ? 'not-allowed' : 'pointer' }}
                  >
                    {isSaving ? '저장 중...' : '변경 저장'}
                  </button>
                </div>
              </div>
            )}

            {/* 리포트 편집기 */}
            <div style={{ backgroundColor: '#bac8ff', padding: '32px', borderRadius: '24px', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
              <div style={{ backgroundColor: '#abc1d1', padding: '8px 24px', borderRadius: '20px', color: 'white', fontSize: '12px', fontWeight: 'bold', marginBottom: '20px' }}>
                📝 자유롭게 내용을 수정하세요! (수정 후 복사 가능)
              </div>
              
              <textarea 
                value={finalReportText}
                onChange={(e) => setFinalReportText(e.target.value)}
                style={{ 
                  backgroundColor: '#fee500', width: '100%', maxWidth: '400px', height: '400px',
                  borderRadius: '16px', padding: '20px', outline: 'none', border: 'none',
                  boxShadow: '0 4px 12px rgba(0,0,0,0.1)', fontFamily: 'Pretendard, sans-serif', 
                  fontSize: '15px', lineHeight: '1.6', color: '#111', resize: 'none'
                }}
              />

              <div style={{ display: 'flex', gap: '12px', marginTop: '24px' }}>
                <button 
                  onClick={handleCopy}
                  style={{ padding: '16px 24px', backgroundColor: '#111', color: 'white', border: 'none', borderRadius: '12px', fontSize: '16px', fontWeight: 'bold', cursor: 'pointer' }}
                >
                  📋 텍스트 복사하기
                </button>
                
                <button 
                  onClick={() => alert("현재 카카오톡 공유 API 연동 준비 중입니다! (다음 스텝에서 구현 예정)")}
                  style={{ padding: '16px 24px', backgroundColor: '#fee500', color: '#111', border: 'none', borderRadius: '12px', fontSize: '16px', fontWeight: 'bold', cursor: 'pointer' }}
                >
                  💬 카톡으로 바로 보내기
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}