import React, { useState, useEffect } from 'react';
import { CONFIG } from '../config';

interface Student {
  id: string;
  name: string;
  currentBook: string;
  progress: string;
  grade: string;
}

interface StudentStats {
  word: number;
  sentence: number;
  ai: number;
  grammar: number;
  retestCount: number;
}

export default function ReportManage() {
  const [students, setStudents] = useState<Student[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedStudent, setSelectedStudent] = useState<Student | null>(null);
  
  const [editBook, setEditBook] = useState('');
  const [editProgress, setEditProgress] = useState('');
  const [isSaving, setIsSaving] = useState(false);

  const [finalReportText, setFinalReportText] = useState('');
  
  // 💡 진짜 학생 성적을 담을 상태 추가!
  const [realStats, setRealStats] = useState<StudentStats>({ word: 0, sentence: 0, ai: 0, grammar: 0, retestCount: 0 });
  const [isStatsLoading, setIsStatsLoading] = useState(false);

  const fetchStudents = async () => {
    try {
      setIsLoading(true);
      const response = await fetch(CONFIG.WEB_APP_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain;charset=utf-8' },
        body: JSON.stringify({ type: "getStudents" })
      });
      const parsedStudents = await response.json();
      if (!parsedStudents.error) {
        setStudents(parsedStudents);
        if (parsedStudents.length > 0) setSelectedStudent(parsedStudents[0]);
      }
    } catch (error) {
      console.error("데이터 로드 실패", error);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { fetchStudents(); }, []);

  // 💡 학생이 바뀔 때마다 진짜 데이터를 가져와서 리포트 생성
  useEffect(() => {
    if (!selectedStudent) return;
    
    setEditBook(selectedStudent.currentBook || '');
    setEditProgress(selectedStudent.progress || '');

    const fetchRealStats = async () => {
      setIsStatsLoading(true);
      try {
        const response = await fetch(CONFIG.WEB_APP_URL, {
          method: 'POST',
          headers: { 'Content-Type': 'text/plain;charset=utf-8' },
          body: JSON.stringify({ 
            type: "getStudentStats", 
            studentId: selectedStudent.id,
            studentName: selectedStudent.name
          })
        });
        const stats: StudentStats = await response.json();
        setRealStats(stats);

        // 데이터가 도착하면 텍스트 리포트 생성
        const today = new Date();
        const weekInfo = `${today.getMonth() + 1}월 ${Math.ceil(today.getDate() / 7)}주차`;
        
        let aiComment = "";
        if (stats.retestCount > 0) {
          aiComment = `특히 이번 주 학습에서 ${stats.retestCount}번의 재도전 끝에 통과해낸 끈기가 매우 훌륭합니다.`;
        } else if (stats.word > 0 || stats.sentence > 0) {
          aiComment = `모든 영역에서 한 번에 통과할 만큼 집중력이 매우 뛰어난 한 주였습니다.`;
        } else {
          aiComment = `아직 이번 주 게임 학습 기록이 없습니다. 다음 주에는 더 활발한 참여를 기대합니다.`;
        }
        
        const autoGeneratedText = `안녕하세요 학부모님! 🐋 고래영어입니다.
${selectedStudent.name} 학생의 ${weekInfo} 주간 분석 리포트입니다.

━━━━━━━━━━━━━━━━
👤 학생: ${selectedStudent.name} (${selectedStudent.grade})
📖 현재 진도: ${selectedStudent.currentBook}권 (${selectedStudent.progress})

📊 [영역별 성취도 분석]
• 단어 암기 (Word): ${stats.word}% 통과
• 문장 배열 (Sentence): ${stats.sentence}% 통과
• 실전 문법 (Grammar): ${stats.grammar}점 획득
• AI 원어민 회화 (Whale Chat): ${stats.ai}% 통과

💬 [원장님 종합 코멘트]
이번 주 ${selectedStudent.name}(이)는 할당된 학습 목표를 훌륭하게 달성했습니다. ${aiComment} 배운 문장들을 바탕으로 실전 감각도 훌륭하게 키우고 있습니다. 주말 동안 가정에서 아낌없는 칭찬 부탁드립니다! 🙇‍♂️
━━━━━━━━━━━━━━━━`;

        setFinalReportText(autoGeneratedText);
      } catch (err) {
        console.error("성적 로드 실패:", err);
      } finally {
        setIsStatsLoading(false);
      }
    };

    fetchRealStats();
  }, [selectedStudent]);

  const handleSaveProgress = async () => {
    if (!selectedStudent) return;
    setIsSaving(true);
    try {
      await fetch(CONFIG.WEB_APP_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain;charset=utf-8' },
        body: JSON.stringify({ type: "updateProgress", studentId: selectedStudent.id, currentBook: editBook, progress: editProgress, sheetName: 'STUDENT_LIST' })
      });
      setStudents(prev => prev.map(s => s.id === selectedStudent.id ? { ...s, currentBook: editBook, progress: editProgress } : s));
      setSelectedStudent(prev => prev ? { ...prev, currentBook: editBook, progress: editProgress } : null);
      alert(`✅ ${selectedStudent.name} 학생의 진도가 변경되었습니다!`);
    } catch (err) {
      alert("진도 업데이트 중 오류가 발생했습니다.");
    } finally {
      setIsSaving(false);
    }
  };

  const ProgressBar = ({ label, percentage, color, isScore = false }: { label: string, percentage: number, color: string, isScore?: boolean }) => (
    <div style={{ marginBottom: '12px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px', fontSize: '13px', fontWeight: 'bold', color: '#475569' }}>
        <span>{label}</span>
        <span>{percentage}{isScore ? '점' : '%'}</span>
      </div>
      <div style={{ width: '100%', height: '12px', backgroundColor: '#e2e8f0', borderRadius: '6px', overflow: 'hidden' }}>
        <div style={{ width: `${isScore ? Math.min(100, (percentage / 1000) * 100) : percentage}%`, height: '100%', backgroundColor: color, transition: 'width 1s ease-in-out' }} />
      </div>
    </div>
  );

  return (
    <div style={{ padding: '30px', backgroundColor: '#f8fafc', minHeight: '100vh', fontFamily: 'Pretendard, sans-serif' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <h2 style={{ margin: 0, fontSize: '28px', fontWeight: '800', color: '#0f172a' }}>💌 주말 리포트 & 실시간 분석</h2>
        <button onClick={fetchStudents} style={{ padding: '10px 16px', backgroundColor: '#e2e8f0', color: '#1e293b', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer' }}>
          🔄 명단/성적 새로고침
        </button>
      </div>

      {isLoading ? (
        <div style={{ textAlign: 'center', padding: '40px' }}>학생 명단을 불러오는 중입니다...</div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 2.5fr', gap: '24px' }}>
          
          <div style={{ backgroundColor: 'white', border: '1px solid #e2e8f0', borderRadius: '16px', overflow: 'hidden', height: 'fit-content' }}>
            <div style={{ backgroundColor: '#f1f5f9', padding: '16px', fontWeight: 'bold' }}>학생 명단</div>
            <div style={{ maxHeight: '700px', overflowY: 'auto' }}>
              {students.map(student => (
                <div 
                  key={student.id} onClick={() => setSelectedStudent(student)}
                  style={{ 
                    padding: '16px', borderBottom: '1px solid #f1f5f9', cursor: 'pointer',
                    backgroundColor: selectedStudent?.id === student.id ? '#eff6ff' : 'white',
                    borderLeft: selectedStudent?.id === student.id ? '4px solid #3b82f6' : '4px solid transparent',
                  }}
                >
                  <div style={{ fontWeight: 'bold', fontSize: '16px' }}>{student.name}</div>
                  <div style={{ color: '#64748b', fontSize: '13px', marginTop: '4px' }}>{student.currentBook}권 | {student.progress}</div>
                </div>
              ))}
            </div>
          </div>

          {selectedStudent && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
              
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                <div style={{ backgroundColor: 'white', padding: '24px', borderRadius: '16px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)' }}>
                  <h3 style={{ margin: '0 0 16px 0', fontSize: '18px', color: '#334155' }}>🛠️ 진도 변경</h3>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                    <input type="text" value={editBook} onChange={(e) => setEditBook(e.target.value)} style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '14px', boxSizing: 'border-box' }} />
                    <input type="text" value={editProgress} onChange={(e) => setEditProgress(e.target.value)} style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '14px', boxSizing: 'border-box' }} />
                    <button onClick={handleSaveProgress} disabled={isSaving} style={{ padding: '12px', backgroundColor: isSaving ? '#94a3b8' : '#3b82f6', color: 'white', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: isSaving ? 'not-allowed' : 'pointer', marginTop: '4px' }}>
                      {isSaving ? '저장 중...' : '변경 내용 저장'}
                    </button>
                  </div>
                </div>

                <div style={{ backgroundColor: 'white', padding: '24px', borderRadius: '16px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)' }}>
                  <h3 style={{ margin: '0 0 16px 0', fontSize: '18px', color: '#334155' }}>📊 실제 데이터 분석</h3>
                  {isStatsLoading ? (
                    <div style={{ padding: '20px', textAlign: 'center', color: '#64748b' }}>데이터를 분석 중입니다...</div>
                  ) : (
                    <div>
                      <ProgressBar label="📝 단어 테스트 (Word)" percentage={realStats.word} color="#3b82f6" />
                      <ProgressBar label="🧩 문장 배열 (Sentence)" percentage={realStats.sentence} color="#10b981" />
                      <ProgressBar label="⚡ 스피드 문법 (Grammar)" percentage={realStats.grammar} color="#8b5cf6" isScore={true} />
                      <ProgressBar label="🤖 AI 대화 (Whale Chat)" percentage={realStats.ai} color="#f59e0b" />
                      
                      <div style={{ marginTop: '16px', padding: '12px', backgroundColor: '#f8fafc', borderRadius: '8px', fontSize: '13px', color: '#475569' }}>
                        💡 <b>도전 기록:</b> 이번 주 총 <b>{realStats.retestCount}번</b>의 재시험 극복 기록이 있습니다!
                      </div>
                    </div>
                  )}
                </div>
              </div>

              <div style={{ backgroundColor: '#bac8ff', padding: '32px', borderRadius: '24px', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                <textarea 
                  value={finalReportText}
                  onChange={(e) => setFinalReportText(e.target.value)}
                  style={{ backgroundColor: '#fee500', width: '100%', maxWidth: '450px', height: '420px', borderRadius: '16px', padding: '20px', outline: 'none', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)', fontFamily: 'Pretendard, sans-serif', fontSize: '14px', lineHeight: '1.6', color: '#111', resize: 'none' }}
                />
                <button onClick={async () => { await navigator.clipboard.writeText(finalReportText); alert('복사되었습니다!'); }} style={{ padding: '16px 24px', backgroundColor: '#111', color: 'white', border: 'none', borderRadius: '12px', fontSize: '16px', fontWeight: 'bold', cursor: 'pointer', marginTop: '24px' }}>
                  📋 리포트 텍스트 복사하기
                </button>
              </div>

            </div>
          )}
        </div>
      )}
    </div>
  );
}