import React, { useState, useEffect, useMemo } from 'react';
import { CONFIG } from '../config';

interface Student {
  id: string;
  name: string;
  currentBook: string;
  progress: string;
  grade: string;
}

export default function ReportManage() {
  const [students, setStudents] = useState<Student[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedStudent, setSelectedStudent] = useState<Student | null>(null);
  
  // 💡 [수정] 원장님이 직접 타이핑하고 수정할 수 있는 최종 리포트 텍스트 상태
  const [finalReportText, setFinalReportText] = useState('');

  // 1. 학생 명단 불러오기
  const fetchStudents = async () => {
    try {
      setIsLoading(true);
      const response = await fetch(`${CONFIG.SHEETS.STUDENT_LIST}&_nocache=${Date.now()}`);
      const text = await response.text();
      const rows = text.split('\n').slice(1).filter(row => row.trim() !== '');
      
      const parsedStudents = rows.map(row => {
        const cols = row.split(',').map(col => col.replace(/"/g, '').trim());
        return {
          id: cols[0], name: cols[1], currentBook: cols[2], progress: cols[3], grade: cols[4]
        };
      });
      
      setStudents(parsedStudents);
      if (parsedStudents.length > 0) setSelectedStudent(parsedStudents[0]);
    } catch (error) {
      console.error("데이터 로드 실패", error);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { fetchStudents(); }, []);

  // 2. 학생이 바뀔 때마다 '기본 리포트 템플릿' 자동 생성
  useEffect(() => {
    if (!selectedStudent) return;
    
    const today = new Date();
    const weekInfo = `${today.getMonth() + 1}월 ${Math.ceil(today.getDate() / 7)}주차`;
    
    const autoGeneratedText = `안녕하세요 학부모님! 🐋 고래영어입니다.
${selectedStudent.name} 학생의 ${weekInfo} 주간 학습 리포트를 보내드립니다.

━━━━━━━━━━━━━━━━
👤 학생: ${selectedStudent.name} (${selectedStudent.grade})
📖 현재 교재: ${selectedStudent.currentBook}권
🎯 현재 진도: ${selectedStudent.progress}

[이번 주 달성 미션 🏆]
✅ 영단어 완벽 암기 통과
✅ 어순 감각 문장 배열 통과
✅ 핵심 문법 퀴즈 통과
━━━━━━━━━━━━━━━━

💬 원장님 코멘트:
이번 주도 결석 없이 성실하게 학습을 완료했습니다. 가정에서도 우리 ${selectedStudent.name}(이)가 성취감을 느낄 수 있도록 아낌없는 폭풍 칭찬 부탁드립니다! 감사합니다. 🙇‍♂️🙇‍♀️`;

    // 생성된 텍스트를 수정 가능한 상태(State)에 집어넣습니다.
    setFinalReportText(autoGeneratedText);
  }, [selectedStudent]);

  // 3. 복사 기능
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(finalReportText);
      alert('복사되었습니다! 카톡에 붙여넣기 하세요.');
    } catch (err) {
      alert('복사 실패');
    }
  };

  return (
    <div style={{ padding: '30px', backgroundColor: '#f8fafc', minHeight: '100vh', fontFamily: 'Pretendard, sans-serif' }}>
      <h2 style={{ margin: 0, fontSize: '28px', fontWeight: '800', color: '#0f172a', marginBottom: '24px' }}>💌 주말 리포트 자동 생성기</h2>

      {isLoading ? (
        <div style={{ textAlign: 'center', padding: '40px' }}>데이터를 불러오는 중입니다...</div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '24px' }}>
          
          {/* 왼쪽: 학생 리스트 */}
          <div style={{ backgroundColor: 'white', border: '1px solid #e2e8f0', borderRadius: '16px', overflow: 'hidden' }}>
            <div style={{ backgroundColor: '#f1f5f9', padding: '16px', fontWeight: 'bold' }}>학생 명단</div>
            <div style={{ maxHeight: '600px', overflowY: 'auto' }}>
              {students.map(student => (
                <div 
                  key={student.id} 
                  onClick={() => setSelectedStudent(student)}
                  style={{ 
                    padding: '16px', borderBottom: '1px solid #f1f5f9', cursor: 'pointer',
                    backgroundColor: selectedStudent?.id === student.id ? '#eff6ff' : 'white',
                    borderLeft: selectedStudent?.id === student.id ? '4px solid #3b82f6' : '4px solid transparent',
                  }}
                >
                  <div style={{ fontWeight: 'bold', fontSize: '16px' }}>{student.name}</div>
                  <div style={{ color: '#64748b', fontSize: '13px' }}>{student.currentBook}권</div>
                </div>
              ))}
            </div>
          </div>

          {/* 오른쪽: [수정 가능해진] 리포트 편집기 */}
          <div style={{ backgroundColor: '#bac8ff', padding: '32px', borderRadius: '24px', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
            <div style={{ backgroundColor: '#abc1d1', padding: '8px 24px', borderRadius: '20px', color: 'white', fontSize: '12px', fontWeight: 'bold', marginBottom: '20px' }}>
              📝 자유롭게 내용을 수정하세요! (수정 후 복사 가능)
            </div>
            
            {/* 💡 핵심: pre 태그를 textarea로 변경하여 편집 가능하게 만듦! */}
            <textarea 
              value={finalReportText}
              onChange={(e) => setFinalReportText(e.target.value)}
              style={{ 
                backgroundColor: '#fee500', width: '100%', maxWidth: '400px', height: '400px',
                borderRadius: '16px', padding: '20px', outline: 'none', border: 'none',
                boxShadow: '0 4px 12px rgba(0,0,0,0.1)', fontFamily: 'Pretendard, sans-serif', 
                fontSize: '15px', lineHeight: '1.6', color: '#111', resize: 'none'
              }}
            />

            <div style={{ display: 'flex', gap: '12px', marginTop: '24px' }}>
              <button 
                onClick={handleCopy}
                style={{ padding: '16px 24px', backgroundColor: '#111', color: 'white', border: 'none', borderRadius: '12px', fontSize: '16px', fontWeight: 'bold', cursor: 'pointer' }}
              >
                📋 텍스트 복사하기
              </button>
              
              {/* 차후 구현될 '다이렉트 카톡 전송' 버튼 미리 배치 */}
              <button 
                onClick={() => alert("현재 카카오톡 공유 API 연동 준비 중입니다! (다음 스텝에서 구현 예정)")}
                style={{ padding: '16px 24px', backgroundColor: '#fee500', color: '#111', border: 'none', borderRadius: '12px', fontSize: '16px', fontWeight: 'bold', cursor: 'pointer' }}
              >
                💬 카톡으로 바로 보내기
              </button>
            </div>

          </div>
        </div>
      )}
    </div>
  );
}